wso2:
  subscription:
    username: ""
    password: ""
  deployment:
    persistentRuntimeArtifacts:
      nfsServerIP: ""
      sharedPubStoreTMLocationPath: ""
      sharedGatewayLocationPath: ""
      sharedISKMLocationPath: ""

kubernetes:
  namespace: "wso2"
  svcaccount: "wso2svc-account"
